### ISSUE TITLE
Undefined reference to 'xvid-global'

### ISSUE THREAD

**Issue by danger5** [soyokaze/SCXvid-standalone#1]
Sorry for bothering, but I'm trying to run `cc -lxvidcore -o scxvid scxvid.c` in Ubuntu, and I get error messages like 'undefined reference to 'xvid-global', 'xvid-encore' and so on. I'm new to Linux, and know nothing about compiling soft, and I've installed 'libxvidcore-dev' but don't know how to check if it is in the compiler's path. I would really appreciate any help.

**Comment by danger5** [comment]
I've figured it out by myself. Cheers!

**Comment by emk2203** [comment]
Could you please let us know what you did to figure this out? Same issue here, I don't want to reinvent the wheel.

**Comment by soyokaze** [comment]
Move `-lxvidcore` to the end, so that the command looks like this: `cc -o scxvid scxvid.c -lxvidcore`.

Putting it at the beginning probably works only for Clang, which I used for building this project.
I'm sorry for skipping proper testing and just leaving it like this.

**Comment by emk2203** [comment]
Thanks. Worked like a charm.
