### ISSUE TITLE
fatal error: xvid.h: No such file or directory

### ISSUE THREAD

**Issue by isrealityreallyreal** [soyokaze/SCXvid-standalone#3]
After extracting the tarball of the latest release, I see the following contents in the `SCXvid-standalone-r1` directory:
```
README.md  SCXvid.sln  SCXvid.vcxproj  SCXvid.vcxproj.filters  scxvid.c
```

Then, when I run
```
cc -o scxvid scxvid.c -lxvidcore
```
in the terminal, I get the following output:
```
scxvid.c:4:10: fatal error: xvid.h: No such file or directory
 #include <xvid.h>
          ^~~~~~~~
compilation terminated.
```
Since there is no `xvid.h` file provided in this package, I assume this was meant to reference an already installed package, and the only dependency mentioned in the readme is `libxvidcore`, so I checked, and I have `libxvidcore4` installed, version `2:1.3.5-1`. This is admittedly a newer version than the readme suggests. Do I need to downgrade it? Or is there some other package I'm missing?

If it matters, I am attempting this on Debian 10 buster with x86_64 architecture. For the record, everything works fine when I use the AUR package on a different computer running Arch.

**Comment by soyokaze** [comment]
Apologies for the late reply.

In mainstream Linux distros, such as Ubuntu, Debian and Fedora, libraries usually come in at least two packages: a main package that contains the shared library file, sufficient for running pre-compiled binaries that are linked with it, and an extra package "for development" that contains C header files and static libraries, required to compile new binaries using the library. Sometimes there are even more extra packages, with documentation, debug symbols etc.

So in this case, besides `libxvidcore4` you need to install `libxvidcore-dev`, and that should make it work.

Geek-oriented distros like Arch or Gentoo don't split library packages like that, so no extra steps are needed there.

**Comment by isrealityreallyreal** [comment]
Can confirm this is working now.
